### ISSUE TITLE
[Node version picker] Deployment is reported as failed but app is still deployed when an invalid node version is specified

### ISSUE THREAD

**Issue by yaminij** [projectkudu/kudu#676]
The issue was sitting around in private kudu at https://github.com/WindowsAzure/kudu/issues/295

Issue: 
1. clone app from https://github.com/KuduApps/InvalidNodeVersion.git
2. Create a new web site and push this app

Expected:
The web site should not have been deployed if we get a deployment failure. 

Actual:
We get a deployment failure and a message "Changes committed to remote repository but your website not updated". However the website is updated with all files from the InvalidNodeVersion app.

Proposed Solutions:
The message at the end of the deployment "Changes committed to remote repository but your website not updated." is incorrect. We have to either
 1) Validate package.json to ensure it has the right node version before copying to the root of the site and fail otherwise.
 2) As a quick fix, change the error message so the user is aware that the site is indeed updated. 

Trace of git push:

```
Compressing objects: 100% (24/24), done.
 Writing objects: 100% (25/25), 5.97 KiB, done.
 Total 25 (delta 8), reused 0 (delta 0)
 remote: Updating branch 'master'.
 remote: Updating submodules.
 remote: Preparing deployment for commit id 'ead16037a3'.
 remote: Generating deployment script.
 remote: Generating deployment script for node.js Web Site
 remote: Running deployment command...
 remote: Handling node.js deployment.
 remote: KuduSync.NET from: 'C:\DWASFiles\Sites\kudusite2\VirtualDirectory0\site\
 repository' to: 'C:\DWASFiles\Sites\kudusite2\VirtualDirectory0\site\wwwroot'
 remote: Deleting file: 'hostingstart.html'
 remote: Copying file: '.gitignore'
 remote: Copying file: 'index.jade'
 remote: No available node.js version matches application's version constraint of  '<0.6.17'.
 remote: Copying file: 'package.json'
 remote: Use package.json to choose one of the available versions.
 remote: Copying file: 'README.md'
 remote: Copying file: 'server.js'
 remote: Copying file: 'public\stylesheets\mixins.styl'
 remote: Copying file: 'public\stylesheets\style.css'
 remote: Copying file: 'public\stylesheets\style.styl'
 remote: Node.js versions available on the platform are: 0.6.17, 0.6.20, 0.8.19,
 0.8.2.
 remote: An error has occurred during web site deployment.
 remote:
 remote: Error - Changes committed to remote repository but your website not updated.
```
